// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ACol: typeof import('ant-design-vue/es')['Col']
    ARow: typeof import('ant-design-vue/es')['Row']
    DBView: typeof import('./src/components/DBView.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MapView: typeof import('./src/components/MapView.vue')['default']
    RegView: typeof import('./src/components/RegView.vue')['default']
    TextView: typeof import('./src/components/TextView.vue')['default']
  }
}

export { }
